spring:
  cloud:
    gateway:
      routes:
      - id: auth-service
        uri: http://auth-service:8081
        predicates: 
           - Path=/api/auth/**
           
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
