spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/api/product/**
        - id: auth-swagger-config-redirect
          uri: lb://auth-service
          predicates:
            - Path=/v3/api-docs/swagger-config
          filters:
            - RewritePath=/v3/api-docs/swagger-config, /auth-service/v3/api-docs         

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret-key: PfbQBaBhujiLiq1htDnUaCO60rvxBLDzCclt/cLGh8g=
  expiration: 86400000
