spring:
  application:
    name: gateway-server
  cloud:
    gateway:
      routes:
      - id: auth-service
        uri: lb://AUTH-SERVICE
        predicates: 
           - Path=/api/auth/**
           
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
